language: node_js
node_js:
  - "8"
  - "10"
  - "12"
before_install:
- export TZ=Europe/Oslo
after_success:
- npm run coverage
notifications:
  email:
    recipients:
      - post@kjellmorten.no
    on_success: never # default: change
    on_failure: always # default: always
